networkId: N78nJXebQmzsBPqeMp7PCfkGXfvKBHMNAieQqi6kEEvTGTHo
nodes:
    - peerId: 12D3KooWSfUD1oayDjfLMaiPdTQFyvVBPrAyX1BQnd7bmrcRD6TU
      addresses:
        - steamdeck
        - 192.168.1.1:4830
      types:
        - coordinator
    - peerId: 12D3KooWAXD6upFrCDA53o5TWNTpTAWCJUrm6vdYvYQfEKeuCoUx
      addresses:
        - steamdeck
        - 192.168.1.1:4430
      types:
        - tree
    - peerId: 12D3KooWByhSQNgY13Ju8gEgq5NVrtn9yJPk3Lasy4BwVDbRUqUV
      addresses:
        - steamdeck
        - 192.168.1.1:4730
      types:
        - file